# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.





# Basic Site Settings
locale                   : "zh-CN"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "徐昕哲"
title_separator          : "-"
name                     : &name "徐昕哲"
description              : &description "南京大学新闻传播学院硕士研究生｜数字营销传播"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://Lemcous.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "Lemcous/Lemcous.github.io"

# Publish standalone pages stored in the _pages directory
include:
  - _pages




# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "IMG_8580.JPG"
  name             : "徐昕哲"
  pronouns         : # example: "she/her"  
  bio              : "南京大学新闻传播学院硕士研究生，研究方向为数字营销传播。"
  location         : "江苏 南京"
  employer         : "南京大学新闻传播学院"
  uri              : # URL
  email            : "Lemcous@163.com" 




  # Academic websites
  academia         : # URL
